ZupIT/horusec-docs

content/en/cli/installation.md
content/en/cli/resources.md
content/en/faq.md
content/en/tutorials/how-to-add-security-tools-to-horusec.md
content/en/tutorials/how-to-classify-a-vulnerability.md
content/en/tutorials/how-to-enable-disable-messaging-service.md
content/en/tutorials/how-to-enable-git-history-analysis-and-enable-commit-authors.md
content/en/tutorials/how-to-run-horusec-multiples-directories.md
content/en/tutorials/how-to-run-the-web-application-on-other-host.md
content/en/tutorials/how-to-use-horusec-without-docker.md
content/en/web/installation/install-with-helm.md
content/en/web/services/migration.md
content/pt-br/cli/installation.md
content/pt-br/cli/resources.md
content/pt-br/faq.md
content/pt-br/tutorials/how-to-classify-a-vulnerability.md
content/pt-br/tutorials/how-to-enable-disable-messaging-service.md
content/pt-br/tutorials/how-to-enable-git-history-analysis-and-enable-commit-authors.md
content/pt-br/tutorials/how-to-run-horusec-multiple-directories.md
content/pt-br/tutorials/how-to-run-the-web-application-on-other-host.md
content/pt-br/tutorials/how-to-setup-tool.md

- Reviewed doc in Portuguese and English;
- Fixed broken links;
- Corrected typos;
- Translated some missing lines in the ENG section;

Documentation review

---

content/en/overview.md

**- What I did** Translated a sentence in Overview section. 
**- Description for the changelog** Translate overview sentence

Translate overview sentence

---

.github/workflows/release-drafter.yml

chore: add release drafter action

---

content/en/web/installation/install-with-helm.md
content/pt-br/web/installation/install-with-helm.md

This pull request is addressed to fix #46.

Fix PostgreSQL and RabbitMQ configurations 

---

content/en/cli/analysis-tools/open-source-horusec-engine/overview.md
content/en/extensions/visual-studio-code.md
content/en/web/installation/install-with-docker-compose.md
content/en/web/services/api.md
content/pt-br/extensions/visual-studio-code.md
content/pt-br/web/installation/install-with-docker-compose.md
content/pt-br/web/services/api.md

- Fixed minor link errors;
- Translated a section on the 'VSCode' section, there were missing images and text.
- Put some links in bold.

Review: fixed minor errors

---

content/en/release-notes.md
content/pt-br/release-notes.md
package-lock.json

**- What I did** Added new release notes, Portuguese version. 
**- How to verify it** 
**- Description for the changelog** New release notes > Portuguese version.

Added new release notes

---

content/en/release-notes.md
content/pt-br/release-notes.md

- Added Release Notes English section.
- Added link to horusec admin. 
**- How to verify it** 
**- Description for the changelog** Release Notes English version.

Added release notes english version

---

content/en/web/installation/install-with-docker-compose.md

Fixing make install cmd tutorial

---

.github/workflows/prepare-release.yml
.github/workflows/proxy/index.html

set github action release note versions

chore: set github action release note versions

---

content/en/cli/installation.md
content/pt-br/cli/installation.md

Fixing cli installationg

---

content/en/tutorials/how-to-add-security-tools-to-horusec.md
content/en/tutorials/how-to-add-tools-using-horusec-engine.md
content/pt-br/tutorials/how-to-add-security-tools-to-horusec.md
content/pt-br/tutorials/how-to-add-tools-using-horusec-engine.md
package-lock.json

Adding new tutorials how to add tools on horusec

---

content/en/migrate-v1-to-v2.md
content/en/release-notes.md
content/pt-br/release-notes.md

**- What I did**: Added new information on the Release Notes section, Portuguese and English.
**- Description for the changelog** Added new information on the Release Notes section, Portuguese and English.

Added new info on Release Notes

---

content/pt-br/tutorials/how-to-add-tools-using-horusec-engine.md

Update formatter example

---

content/en/cli/analysis-tools/open-source-horusec-engine/horusec-swift.md
content/pt-br/cli/analysis-tools/open-source-horusec-engine/horusec-swift.md

add Swift rules docs

---

content/en/cli/analysis-tools/overview.md
content/en/release-notes.md
content/en/tutorials/how-to-add-tools-using-horusec-engine.md
content/en/web/services/manager/introduction.md
content/pt-br/tutorials/how-to-add-tools-using-horusec-engine.md

- Added new release notes in English
- Updated tutorials section in English
- Added new Swift language 

Added new release notes and fixed other pages

---

content/en/cli/analysis-tools/overview.md
content/pt-br/cli/analysis-tools/overview.md

Fix some bugs

---

content/en/cli/analysis-tools/overview.md
content/en/cli/analysis-tools/security-tools.md
content/en/cli/resources.md
content/pt-br/cli/analysis-tools/overview.md
content/pt-br/cli/analysis-tools/security-tools.md
content/pt-br/cli/resources.md
resources/_gen/assets/scss/docs/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content

- Added new information about Owasp Dependency Check to: 
> CLI > Overview
> CLI > Other Tools section
> CLI > Resources  
- Portuguese and English versions. 
**- Description for the changelog** Added new information about Owasp Dependency Check

Added new information about Owasp Dependency Check

---

content/en/cli/analysis-tools/open-source-horusec-engine/horusec-swift.md
content/en/cli/analysis-tools/overview.md
content/en/cli/analysis-tools/security-tools.md
content/en/cli/resources.md
content/en/release-notes.md
content/pt-br/cli/analysis-tools/open-source-horusec-engine/horusec-swift.md
content/pt-br/cli/analysis-tools/overview.md
content/pt-br/cli/analysis-tools/security-tools.md
content/pt-br/cli/resources.md
content/pt-br/release-notes.md

-  Added new title and description to Horusec-Swift page;
-  Added new table on Analysis Tools>Overview section;
-  Added new information to the Release Notes section;
-   Corrected some issues reported by the team; 
-  Added new tool DotNet CLI to the Analysis Tools section.
**- Description for the changelog** Added new information and updated the documentation

Added new tools and other updates

---

content/en/cli/analysis-tools/overview.md
content/en/cli/analysis-tools/security-tools.md
content/en/cli/resources.md
content/en/release-notes.md
content/pt-br/cli/analysis-tools/overview.md
content/pt-br/cli/analysis-tools/security-tools.md
content/pt-br/cli/resources.md
content/pt-br/release-notes.md

- Added Nancy to Security Tools > Overview and Resources
- Added a new bug fix in Release Notes 
**- Description for the changelog** 
- Added new security tool and updated Release Notes

Added new security tool and updated RN

---

content/en/web/installation/install-with-helm.md
content/pt-br/web/installation/install-with-helm.md

Removed '-Linux' from Installing with Helm requirements. 

Removed linux from installing with helm

---

content/pt-br/web/installation/install-with-operator.md

Fixed a typo in the installation section > Instale com Operator

fixed minor typo

---

content/pt-br/web/overview.md

What I did read the overview page
How to verify it read the overview page
Description for the changelog
Suggestion to change the text on the overview page (Sugestão de correção de grafia e adequação do texto.)
Original text (Texto original):
Quais funcinários que estão subindo essas possíveis vulnerabilidades gerando uma falha em seu projeto e quais são suas classificações.
Suggestion (Sugestão):
Quais funcionários estão subindo essas possíveis vulnerabilidades gerando uma falha em seu projeto e quais são suas classificações.

Sugestão de correção de grafia e adequação do texto.

---

content/en/cli/resources.md
content/en/release-notes.md
content/pt-br/cli/resources.md
content/pt-br/release-notes.md
content/pt-br/web/installation/install-with-admin.md

- Added new flag and information on CLI > Resources 
- Added new content on Release Notes Section
**- Description for the changelog** New info on Resources and Release Notes.

Added new flag on resources

---

content/en/cli/resources.md
content/en/release-notes.md
content/pt-br/cli/resources.md
content/pt-br/release-notes.md

- Added new flag: HORUSEC_CLI_LOG_FILE_PATH="./tmp".
- Added new info in the Release Notes section. 

Added new flag and release notes

---

content/en/cli/analysis-tools/overview.md
content/en/cli/overview.md
content/en/faq.md
content/en/overview.md
content/en/web/installation/install-with-docker-compose.md
content/en/web/overview.md
content/en/web/services/auth.md
content/en/web/services/manager/introduction.md
content/en/web/services/messages.md
content/en/web/services/vulnerability.md
content/pt-br/cli/analysis-tools/overview.md
content/pt-br/cli/overview.md
content/pt-br/faq.md
content/pt-br/overview.md
content/pt-br/web/installation/install-with-docker-compose.md
content/pt-br/web/overview.md
content/pt-br/web/services/auth.md
content/pt-br/web/services/manager/introduction.md
content/pt-br/web/services/messages.md
content/pt-br/web/services/vulnerability.md

- Changed the Overview structure;
- Changed CLI > Overview;
- Changed Analysis tools > Overview;
- Added a hint in 'Installing with Docker';
- Added 'Read more + links' throughout the documentation; 
- Added new questions to the FAQ. 
Changes made: Portuguese + English versions. 

Changes in the documentation

---

content/en/development-environment.md
content/en/web/installation/install-with-docker-compose.md
content/en/web/installation/install-with-helm.md
content/en/web/installation/install-with-operator/overview.md
content/en/web/set-up.md
content/pt-br/development-environment.md
content/pt-br/web/installation/install-with-docker-compose.md
content/pt-br/web/installation/install-with-helm.md
content/pt-br/web/installation/install-with-operator/overview.md
content/pt-br/web/set-up.md
resources/_gen/assets/scss/docs/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content

- Fixed some issues in the Installing section; 
- Moved the requirements to a new section called 'Set up'; 
- Moved the Environment Development to a new section;
- Fixed some typos.
- 

Fixed issues on Installing section

---

content/pt-br/cli/installation.md

- Added manual installation information for MacOS and Linux operating systems. 

Information added in the installation section

---

content/en/cli/installation.md

Installation: Update link to download latest version horusec binaries

---

config.toml
content/en/faq.md
content/pt-br/faq.md
layouts/partials/navbar.html

add faq to main menu, change footer links

feat: add faq to main menu, change footer links

---

content/pt-br/tutorials/how-to-add-security-tools-to-horusec.md
content/pt-br/tutorials/how-to-add-tools-using-horusec-engine.md

Signed-off-by: Matheus Alcantara <matheus.alcantara@zup.com.br>

fix how to add new horusec engine and security tool

---

.gitmodules
resources/_gen/assets/scss/docs/scss/main.scss_9fadf33d895a46083cdd64396b57ef68.content

search on docs and forum open source

feat: search on docs and forum open source

---

content/en/cli/analysis-tools/overview.md
content/en/cli/installation.md
content/en/development-environment.md
content/en/migrate-v1-to-v2.md
content/en/web/installation/install-with-operator/overview.md
content/en/web/installation/install-with-operator/yaml-definition.md
content/pt-br/cli/analysis-tools/overview.md
content/pt-br/cli/installation.md
content/pt-br/development-environment.md
content/pt-br/migrate-v1-to-v2.md
content/pt-br/web/installation/install-with-operator/overview.md
content/pt-br/web/installation/install-with-operator/yaml-definition.md

Signed-off-by: wilian <wilian.silva@zup.com.br>

Fix correct version in doc

---

content/en/tutorials/how-to-adding-custom-rules.md
content/pt-br/tutorials/how-to-adding-custom-rules.md

Update ID field description of how to add a custom rules since we do not
use uuid anymore to represents rule id.
Signed-off-by: Matheus Alcantara <matheus.alcantara@zup.com.br>

custom-rules: update id field description

---

content/en/cli/analysis-tools/overview.md
content/en/web/services/core.md
content/pt-br/cli/analysis-tools/overview.md
content/pt-br/web/services/core.md

Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
**- What I did** Added a few updates on documentation: 
- Added HORUSEC_MANAGER_URL to Services >Core
- Added the analysis tools available versions on Horusec-CLI 
**- Description for the changelog** New doc updates and fix.

Added new updates

---

content/en/cli/resources.md
content/pt-br/cli/resources.md

Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
Added information about Docker variables at CLI > Resources.
**- Description for the changelog** Added information about Docker variables.

Added information about Docker variables

---

content/en/cli/resources.md
content/pt-br/cli/resources.md

Add information for the --show-vulnerabilities flag on CLI / Resources section.
Signed-off-by: lucas.bruno <lucas.bruno@zup.com.br>

cli/resources:chore - information for the --show-vulnerabilities flag

---

layouts/partials/hooks/head-end.html

**- What I did** I included GTM into html
**- How to verify it** Take a look at head-end.html

chore:feat - google tag manager

---

.github/workflows/security-pipeline.yml

Signed-off-by: Nathan Martins <nathan.martins@zup.com.br>

workflow/security:chore - updating security workflow to use latest rc

---

content/en/web/installation/install-with-operator/yaml-definition.md
content/pt-br/web/installation/install-with-operator/yaml-definition.md

Signed-off-by: Nathan Martins <nathan.martins@zup.com.br>

operator:bugfix - updating operator crd yaml
